#!/bin/sh

sv_stop() {
        for s in $(ls -d /etc/service/*)
        do
                /usr/sbin/sv stop $s
        done
}

trap "sv_stop; exit" SIGTERM
exec /usr/sbin/runsvdir /etc/service &
wait
